version: "3.1"
services:

  layer1:
    image: tearust/tea-layer1:0.5
    container_name: layer1
    ports:
      - 9944:9944
    volumes:
      - .layer1:/root/.local
    command: bash -c "tea-layer1 --chain dev --ws-external --rpc-external --rpc-cors all --bootnodes /ip4/64.227.57.97/tcp/30333/p2p/12D3KooWK6sbANf86AQ9xokG4PzrwwzMjmUtCuapKE4ZV2tJ43Nn"