version : "3"
services:
  # nat-server:
  #   image: nats:latest
  #   container_name: "nats-server"
  #   ports:
  #     - 4222:4222

  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs
    volumes:
    - ".data/export:/export"
    - ".data/ipfs:/data/ipfs"
    ports:
    - "5002:5001"
    - "4001:4001"
    - "8080:8080"
